### PR TITLE
Update URLs to reference new cross-rs organisation

### PR DESCRIPTION
**Pull request by adamgreig**

### CODE REVIEW

**Comment by Emilgardis** [comment]
bors ping

installed bors, let's see if it works

**Review by Emilgardis — DISMISSED** [review]
bors r+

🎉

**Comment by Emilgardis** [comment]
https://github.com/cross-rs/cross/blob/2f1ef07fdaf92ba31e6d6ce0ab4c5dca63ca0aa7/.github/bors.toml needs to be changed to not include the azure status check

**Comment by adamgreig** [comment]
Thanks, done. I've also added a new `maintainers` team and set them as CODEOWNERS for github's automatic review suggestions, and removed rust-embedded/tools from there.

**Review by Emilgardis — APPROVED** [review]
bors r+

**Pull request merged**
