### PR TITLE
Improve Docker caching.

### PR DESCRIPTION
**Pull request by reitermarkus**
Also use pushed images as cache.

### CODE REVIEW

**Comment by reitermarkus** [comment]
bors try

**Comment by reitermarkus** [comment]
bors try

**Comment by reitermarkus** [comment]
bors try

**Comment by reitermarkus** [comment]
bors try

**Comment by reitermarkus** [comment]
bors try

**Comment by Emilgardis** [comment]
`--cache-from type=registry,ref=ghcr.io/cross-rs/{target}:trying`

it should probably just use `edge`/`main`

**Review by Emilgardis — DISMISSED** [review]
bors r+

**Comment by Emilgardis** [comment]
lets try again

bors r+

**Comment by reitermarkus** [comment]
bors retry

**Review by Emilgardis — APPROVED** [review]
bors r+

**Pull request merged**
