### PR TITLE
Add mips64-unknown-linux-muslabi64 and mips64el-unknown-linux-muslabi64 support

### LINKED ISSUE #503: Support mips64-unknown-linux-muslabi64 and mips64el-unknown-linux-muslabi64
rust has been support both targets: https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2

Hope cross also support soon.

### PR DESCRIPTION
**Pull request by abcfy2**
Fix #503

Reopen from #507

### CODE REVIEW

**Comment by reitermarkus** [comment]
bors try

**Comment by abcfy2** [comment]
> Please add a changelog entry and fix the missing newlines in the Dockerfiles.

How do I add changelog. Is there any examples ?

**Comment by reitermarkus** [comment]
In `CHANGELOG.md`, add a new line under the “Unreleased” section.

**Comment by abcfy2** [comment]
Got it.

**Comment by abcfy2** [comment]
Rebase from main branch, and test should be fixed.

**Comment by Emilgardis** [comment]
bors try --target mips64

**Review by Emilgardis — APPROVED** [review]
Thanks!

bors r+

**Pull request merged**
