### PR TITLE
Always link to libgcc for musl targets.

### LINKED ISSUE #367: armv5te-unknown-linux-musleabi with OpenSSL fails with undefined reference to `__sync_sub_and_fetch_4'
I wonder if this has been fixed?  I cannot seem to be able to make an ARMv5TE build OpenSSL without tripping on this error...

Apparently `__sync_sub_and_fetch_4` _is_ already supplied by the build target lib, because defining my own version also causes multiple-definition errors.  For some reason, the linker just doesn't like to use the library's version.

### LINKED ISSUE #985: Missing intrinsic functions on aarch64/armv7 musl
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

When using `-Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort` on nightly, the [CI](https://github.com/NobodyXu/cargo-binstall/runs/7576062771?check_suite_focus=true) for `armv7-unknown-linux-musleabihf` failed with:

```
error: linking with `arm-linux-musleabihf-gcc` failed: exit status: 1
  |
  = note: "arm-linux-musleabihf-gcc" "/rust/lib/rustlib/armv7-unknown-linux-musleabihf/lib/self-contained/crt1.o" "/rust/lib/rustlib/armv7-unknown-linux-musleabihf/lib/self-contained/crti.o" "/rust/lib/rustlib/armv7-unknown-linux-musleabihf/lib/self-contained/crtbegin.o" "/tmp/rustchhh9b4/symbols.o" "/target/armv7-unknown-linux-musleabihf/release/deps/cargo_binstall-3e50bf6da12c20a5.cargo_binstall.a21ddfed-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/target/armv7-unknown-linux-musleabihf/release/deps" "-L" "/target/release/deps" "-L" "/target/armv7-unknown-linux-musleabihf/release/build/bzip2-sys-c8079e4346e62d12/out/lib" "-L" "/target/armv7-unknown-linux-musleabihf/release/build/ring-ebc6c8a01f6ba0cc/out" "-L" "/target/armv7-unknown-linux-musleabihf/release/build/libz-ng-sys-f0f6c53a33219098/out/lib" "-L" "/target/armv7-unknown-linux-musleabihf/release/build/lzma-sys-b43b0fc572ecbfdb/out" "-L" "/target/armv7-unknown-linux-musleabihf/release/build/zstd-sys-2590e47ee852bb0f/out" "-L" "/rust/lib/rustlib/armv7-unknown-linux-musleabihf/lib" "-Wl,-Bstatic" "/tmp/rustchhh9b4/libzstd_sys-f7d06c8757472495.rlib" "/tmp/rustchhh9b4/liblzma_sys-2e2684a73a1d7334.rlib" "/tmp/rustchhh9b4/liblibz_ng_sys-3508004d4f9f58ad.rlib" "/tmp/rustchhh9b4/libbzip2_sys-d3cb4d953a9c8aa6.rlib" "/tmp/rustchhh9b4/libring-4ed7a44158b48a92.rlib" "-Wl,--start-group" "-lunwind" "-lc" "-Wl,--end-group" "/target/armv7-unknown-linux-musleabihf/release/deps/libcompiler_builtins-6e6f29f70316d02a.rlib" "-Wl,-Bdynamic" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-nostartfiles" "-L" "/rust/lib/rustlib/armv7-unknown-linux-musleabihf/lib" "-L" "/rust/lib/rustlib/armv7-unknown-linux-musleabihf/lib/self-contained" "-o" "/target/armv7-unknown-linux-musleabihf/release/deps/cargo_binstall-3e50bf6da12c20a5" "-Wl,--gc-sections" "-static" "-no-pie" "-Wl,-zrelro,-znow" "-Wl,--strip-all" "-nodefaultlibs" "/rust/lib/rustlib/armv7-unknown-linux-musleabihf/lib/self-contained/crtend.o" "/rust/lib/rustlib/armv7-unknown-linux-musleabihf/lib/self-contained/crtn.o"
  = note: /usr/local/bin/../lib/gcc/arm-linux-musleabihf/9.2.0/../../../../arm-linux-musleabihf/bin/ld: /tmp/rustchhh9b4/liblibz_ng_sys-3508004d4f9f58ad.rlib(compare256_neon.c.o): in function `compare256_neon_static':
          compare256_neon.c:(.text.compare256_neon_static+0x28): undefined reference to `__ctzdi2'
          /usr/local/bin/../lib/gcc/arm-linux-musleabihf/9.2.0/../../../../arm-linux-musleabihf/bin/ld: compare256_neon.c:(.text.compare256_neon_static+0x42): undefined reference to `__ctzdi2'
          collect2: error: ld returned 1 exit status
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `cargo-binstall` due to previous error
Error: Process completed with exit code 101.
```

And the [CI for  aarch64-unknown-linux-musl](https://github.com/NobodyXu/cargo-binstall/runs/7576062950?check_suite_focus=true) failed with similar error.

### What target(s) are you cross-compiling for?

aarch64-unknown-linux-musl, armv7-unknown-linux-musleabihf

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.4 (4645d93 2022-07-10)

### Example

`cross` seems to have missing intrinsic functions on aarch64/armv7 musl build when using `build-std` features:

```bash
cross build --target aarch64-unknown-linux-musl --profile release -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
```

It only happens if we have the `build-std` configurations.

### Additional information / notes

This might be related to #896 

This issue was discovered in https://github.com/ryankurte/cargo-binstall/pull/256 .

### PR DESCRIPTION
**Pull request by Alexhuszagh**
Fixes issues with numerous missing symbols from libgcc routines that are
not currently implemented in Rust's compiler builtins. These include:
- __trunctfsf2
- __ctzdi2
- __letf2
- __addtf3

These missing symbols all seem to be soft-float and integer arithmetic routines. These missing symbols all seem to be soft-float and integer arithmetic routines. This is a temporary workaround until these are all implemented in compiler-builtins.

Closes #367.
Closes #985.

### CODE REVIEW

**Comment by Alexhuszagh** [comment]
bors try --target *linux-musl*

**Comment by Alexhuszagh** [comment]
bors try-
bors try --target musl

**Comment by Alexhuszagh** [comment]
bors try --target mips64-unknown-linux-muslabi64

**Comment by Alexhuszagh** [comment]
It might be worth conditionally disabling this linking to libgcc, since it might obscure missing builtins that need to be patched in `compiler-builtins`.

**Comment by NobodyXu** [comment]
@Alexhuszagh It still failed https://github.com/NobodyXu/cargo-binstall/runs/7589919126?check_suite_focus=true

**Comment by Alexhuszagh** [comment]
> @Alexhuszagh It still failed https://github.com/NobodyXu/cargo-binstall/runs/7589919126?check_suite_focus=true

Right because although you've configured the proper cross version, you haven't built the correct image and are using one from the latest main, so it's still using the wrong linker. I can provide a temporary link on Dockerhub for testing (not an official image, and it will likely be removed in a few days) that you can then provide via `CROSS_TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABIHF_IMAGE`, which will then override the default image. Or, provide it in `Cross.toml`:

```toml
[target.armv7-unknown-linux-musleabihf]
image = "..."
```

**Comment by NobodyXu** [comment]
> Sorry, I might not have been clear that you have to build the image to test the changes.

Oh that's right, I saw you change the `Dockerfile`s but since this PR is not merged it, it is not on the ghcr.

@Alexhuszagh Can you provide a temporary image on dockerhub? Thanks!

**Comment by Alexhuszagh** [comment]
Actually, I think the better issue would be to document how to use `build-std` or provide `-lgcc` as a flag when it's used to `RUSTFLAGS` for any musl or GNU target when the build-std cfg option is provided. Numerous other targets require external C builtins for `build-std` (such as `aarch64-unknown-linux-gnu`), and porting every builtin is a monumental effort. Nor should we obscure potential errors in toolchains due to missing intrinsics for regular builds (IE, without using `build-std`).

So, `CROSS_BUILD_STD` and the TOML variant should likely set `-lgcc` if applicable, we should fix #367 with a GCC linker as well, and we should update the linkers provided in #367 and #974 to no longer link to libgcc when both those patches made to compiler-builtins reaches std.

**Comment by Alexhuszagh** [comment]
@NobodyXu The images for the two targets are provided [here](https://hub.docker.com/repository/docker/ahuszagh/cross-musl-linker). I'll likely update the documentation for how to use `build-std` when external C dependencies are required tomorrow.

**Comment by NobodyXu** [comment]
@Alexhuszagh That fixed the issue https://github.com/NobodyXu/cargo-binstall/actions/runs/2765292275 , thanks, though I cannot merge that PR.

Can using `zig-cc` image fixes this?
And what will be the final solution in cross 0.3.0?

**Pull request closed without merging**
