### PR TITLE
Downgrade musl to 1.1.24

### LINKED ISSUE #478: musl cannot be update to 1.2.0 yet
musl was update to 1.2.0 in https://github.com/rust-embedded/cross/pull/452. The 1.2 changed the definition of time_t from 32 to 64bits, which can generate some compatibility issues (https://musl.libc.org/time64.html).

Considering that libc crate and the rust std library does not yet updated to 1.2.0 (https://github.com/rust-lang/libc/issues/1848) and the problems that can arising by using musl 1.1.x together with 1.2.x, I think it's best to not update musl used in cross images.

CC @brainstorm @therealprof

### PR DESCRIPTION
**Pull request by malbarbo**
Fixes #478.

### CODE REVIEW

**Comment by brainstorm** [comment]
At this point, I think it's best to *NOT* downgrade MUSL on the cross images. A few months have passed with MUSL 1.2.0 merged in and: 

1) It allows OpenSSL to be cross-compiled successfully.
2) I'm not aware of any other specific breakage from apps/users?

@malbarbo Which packages have you seen breaking "in the wild" due to this?

**Comment by malbarbo** [comment]
The problem can happen with any project that interacts with C. See https://github.com/ericonr/rust-time64.

**Comment by reitermarkus** [comment]
Is this still relevant? I'm guessing it is since the `libc` issue is still open, so please rebase this.

**Comment by Alexhuszagh** [comment]
It is, I just tested it with a Dockerfile with OpenSSL. Sample code to reproduce is (based off of [sheldon-cross](https://github.com/rossmacarthur/sheldon-cross)).

**Dockerfile**

```Dockerfile
FROM ghcr.io/cross-rs/armv7-unknown-linux-musleabihf:main

COPY install_openssl.sh /
RUN apt-get update && apt-get install wget
RUN wget https://github.com/rossmacarthur/sheldon-cross/blob/trunk/docker/install_openssl.sh
RUN bash /install_openssl.sh linux-armv4 arm-linux-musleabihf-

ENV OPENSSL_DIR=/openssl \
    OPENSSL_STATIC=1 \
    OPENSSL_INCLUDE_DIR=/openssl/include \
    OPENSSL_LIB_DIR=/openssl/lib
```

Then, set the appropriate target in `Cross.toml` using the local tag, and try to build the image:

```bash
git clone https://github.com/rossmacarthur/sheldon
cd sheldon
cargo build --target armv7-unknown-linux-musleabihf
```

Which produces a lot of errors related to 64-bit time (undefined references to `__time64`, `__fstat_time64`, `__clock_gettime64`, `__stat_time64`, and more). Could we get a rebase or I could make the modifications and merge.

**Review by otavio — APPROVED** [review]

**Pull request merged**
