### PR TITLE
remove extra slash

### PR DESCRIPTION
**Pull request by otavio**
This is a rebase of #544.

### CODE REVIEW

**Review by reitermarkus — APPROVED** [review]

**Comment by Emilgardis** [comment]
[This](https://github.com/cross-rs/cross/pull/544#issuecomment-811796867) comment was not a concern then? I was imagining mount paths specified as relative paths would affect this

**Comment by otavio** [comment]
I don't see why we'd need this. It seems valid to expect users to provide full paths. We can handle relative paths internally if need but seems too magical for me.

**Comment by reitermarkus** [comment]
> I remember there being a specific reason for this. Ill try and dig it up unless someone else knows why.

I couldn't find any specific reason for having the slash there looking through `git blame`. If there is indeed a problem with relative paths we can canonicalize them beforehand, if that isn't already the case.

**Pull request merged**
