### PR TITLE
Add editorconfig file.

### LINKED ISSUE #1089: add a `.editorconfig`
maybe we should add a [`.editorconfig`](https://editorconfig.org/) too while I'm at it and lint on it? Unsure how to lint a `.editorconfig` in a simple way though

_Originally posted by @Emilgardis in https://github.com/cross-rs/cross/pull/1015#discussion_r967640904_

### PR DESCRIPTION
**Pull request by Alexhuszagh**
Closes #1089.

### CODE REVIEW

**Comment by Alexhuszagh** [comment]
The code can be linted via [eclint](https://www.npmjs.com/package/eclint), however, this produces a lot of false positives, especially in inline diff files, which means linting in CI is a waste of time. These are suggestions: not hard rules.

**Review by Emilgardis — APPROVED** [review]
awesome!

bors r+

**Comment by Alexhuszagh** [comment]
bors r=Emilgardis

**Comment by Alexhuszagh** [comment]
I think some of these might be now an unrelated issue and due to the failing being the same one in the non-cached build: `max_kernel_version` isn't picking up anything because the glob expansion doesn't work:
https://github.com/cross-rs/cross/actions/runs/3293850267

**Comment by Alexhuszagh** [comment]
bors r=Emilgardis

**Pull request merged**
