### PR TITLE
fix for real

### PR DESCRIPTION
**Pull request by Emilgardis**
- make env var uppercase

### CODE REVIEW

**Comment by Emilgardis** [comment]
bors try

going to remove version bump on success

**Comment by Emilgardis** [comment]
This i sprobably something we should support, since cargo supports it

**Comment by Emilgardis** [comment]
bors try

**Comment by Emilgardis** [comment]
bors try-

bors try

**Comment by Emilgardis** [comment]
bors try

**Comment by Emilgardis** [comment]
bors try-

bors try

**Review by Alexhuszagh — APPROVED** [review]

**Comment by Emilgardis** [comment]
bors r=Alexhuszagh

**Pull request merged**
