### PR TITLE
change edition to 2021

### PR DESCRIPTION
**Pull request by Emilgardis**
also removes author field as it is not displayed on crates.io anymore.

### CODE REVIEW

**Review by otavio — COMMENTED** [review]
I did the same here but didn't send it as it doesn't use any 2021 specific feature or addition. A side effect is raising the MSRV. Is it a problem?

**Comment by Emilgardis** [comment]
> I did the same here but didn't send it as it doesn't use any 2021 specific feature or addition. A side effect is raising the MSRV. Is it a problem?

msrv is already 1.58, 2021 edition is 1.56.0

**Review by otavio — APPROVED** [review]

**Comment by Emilgardis** [comment]
with color-eyre added, I want to transition all possible instances of `format!("...{}...", thing)` to `format!("...{thing}...")`

**Review by reitermarkus — APPROVED** [review]

**Review by otavio — APPROVED** [review]

**Pull request merged**
