### PR TITLE
Link to libgcc for `armv5te-unknown-linux-musleabi` target.

### LINKED ISSUE #367: armv5te-unknown-linux-musleabi with OpenSSL fails with undefined reference to `__sync_sub_and_fetch_4'
I wonder if this has been fixed?  I cannot seem to be able to make an ARMv5TE build OpenSSL without tripping on this error...

Apparently `__sync_sub_and_fetch_4` _is_ already supplied by the build target lib, because defining my own version also causes multiple-definition errors.  For some reason, the linker just doesn't like to use the library's version.

### PR DESCRIPTION
**Pull request by Alexhuszagh**
Fixes missing sync builtins required for libraries such as OpenSSL, specifically, the `__sync_X_and_fetch` builtins.

Closes #367.
Improves documentation related to #906.

### CODE REVIEW

**Comment by Emilgardis** [comment]
I'm not sure this is something we should do since it's an upstream issue and will eventually e fixed hopefully.

**Comment by Alexhuszagh** [comment]
> I'm not sure this is something we should do since it's an upstream issue and will eventually be fixed hopefully.

It is, it's already been patched (I submitted https://github.com/rust-lang/compiler-builtins/pull/484 which was merged), but we need to wait for a stable release similar to what we do in [aarch64-linux-musl-gcc.sh](https://github.com/cross-rs/cross/blob/main/docker/aarch64-linux-musl-gcc.sh)

**Review by Emilgardis — APPROVED** [review]
let's merge this, we can add a version check later maybe?

r=me if ok

**Comment by Alexhuszagh** [comment]
bors r=Emilgardis

**Review by Emilgardis — APPROVED** [review]

**Comment by Alexhuszagh** [comment]
bors try --target mips64-unknown-linux-muslabi64

**Comment by Alexhuszagh** [comment]
bors r=Emilgardis

**Pull request merged**
