### PR TITLE
Explicitly prefer `-ar` to `-gcc-ar`.

### LINKED ISSUE #1100: archiver in freebsd images appears to be broken
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

The toolchain used in the freebsd images appears to be broken. I managed to reduce the test case basically down to just:

```shell
$ docker pull ghcr.io/cross-rs/x86_64-unknown-freebsd:0.2.4
$ docker run -it ghcr.io/cross-rs/x86_64-unknown-freebsd:0.2.4 bash
$ echo "int banana(void) { return 0; }" | x86_64-unknown-freebsd12-gcc -xc - -c -o chaenomeles.o
$ x86_64-unknown-freebsd12-gcc-ar cq mango.ar chaenomeles.o; echo $?
x86_64-unknown-freebsd12-gcc-ar: Cannot find plugin 'liblto_plugin.so'
1
```

This in practice causes crates such as `cc` fail to package the built objects into an `.a` in crates’ build.rs scripts.

### What target(s) are you cross-compiling for?

i686-unknown-freebsd, x86_64-unknown-freebsd

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.4

### Example

_No response_

### Additional information / notes

The closest relevant thing I can find on the internet is https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81326. Curiously we are already building the toolchain with `--disable-lto` flag, so it might be a bug in gcc itself?

### PR DESCRIPTION
**Pull request by Alexhuszagh**
Fixes #1100.

### CODE REVIEW

**Comment by Alexhuszagh** [comment]
bors try --target *-none-* --target *-freebsd --target *-dragonfly --target *-solaris --target *-illumos *-netbsd

**Comment by Alexhuszagh** [comment]
Note I didn't provide `AR_$target` for the Android images, since these are provided in #1023.

**Review by Emilgardis — APPROVED** [review]
this change is parallel to https://github.com/rust-lang/cc-rs/pull/741, but this is fine standalone and resolves issues for people locked to `cc="=1.0.74"`

bors r+

**Comment by svenstaro** [comment]
Can we get a release containing this? Otherwise this is currently broken by default.

**Comment by Alexhuszagh** [comment]
I don't think 0.3.0 is quite ready for release, especially not in the next week or so, but this is a trivial patch so we could backport it and do a quick release for 0.2.5?

**Comment by Emilgardis** [comment]
cc 1.0.75 has been released. https://github.com/rust-lang/cc-rs/pull/741#issuecomment-1307514624

hopefully this solves the problem enough

**Pull request merged**
