### PR TITLE
Update zig-cc and zigbuild versions.

### PR DESCRIPTION
**Pull request by sagudev**

### CODE REVIEW

**Comment by sagudev** [comment]
Currently fails with:
```
   running: "/target/.zig-cache/cargo-zigbuild/0.17.2/zigcxx-i586-unknown-linux-musl.sh" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m32" "-march=pentium" "-Wl,-melf_i386" "-Wall" "-Wextra" "-o" "/target/i586-unknown-linux-musl/debug/build/hellopp-a1a57f003a4c4646/out/hellopp.o" "-c" "hellopp.cc"
  cargo:warning=error: unsupported linker arg: -melf_i386
```

**Comment by Emilgardis** [comment]
bors try --target zig

**Comment by sagudev** [comment]
Given that we already h[ave warnings in current builds](https://github.com/cross-rs/cross/actions/runs/5897187909/job/15996431996#step:11:165) this must be https://github.com/rust-cross/cargo-zigbuild/issues/96.

**Review by Emilgardis — APPROVED** [review]
Thanks!

bors r+

**Comment by sagudev** [comment]
I do not think that try build works as there was no zig test run.

**Comment by thomas725** [comment]
Okey, looking at the previous changelog entries I see the issue property is optional, so I created one without.

**Pull request merged**
