### PR TITLE
docker: Add Nix Store volume support

### PR DESCRIPTION
**Pull request by otavio**
When running inside NixOS or using Nix packaging we need to add the Nix
Store to the running container so it can load the needed binaries.

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

### CODE REVIEW

**Comment by otavio** [comment]
The error on the pipeline does not seem related. Any idea what might have caused it?

**Comment by otavio** [comment]
> The error on the pipeline does not seem related. Any idea what might have caused it?

This is indeed not related. See:
```
E: Unable to locate package linux-image-4.19.0-11-arm64:arm64
E: Couldn't find any package by glob 'linux-image-4.19.0-11-arm64'
E: Couldn't find any package by regex 'linux-image-4.19.0-11-arm64'
```

**Comment by otavio** [comment]
Any news on this?

**Comment by reitermarkus** [comment]
What is the use case for this? It seems like this should already be possible using `env.volumes`.

**Comment by otavio** [comment]
It fails to run automatically; so we would need to pass it to every time we call cross when using NixOS.

**Comment by reitermarkus** [comment]
> It fails to run automatically

What exactly fails to run? I'm not really familiar with NixOS, can you explain in more detail which packages need to be available/mounted in the container and why?

**Comment by otavio** [comment]
I am unsure if you know what NixOS is. So please take a look at [How Nix works](https://nixos.org/guides/how-nix-works.html) document. It explains how the Nix store works and more.

In summary, without the patch, `cross` fails to run because _it cannot find the binaries it runs inside the container_. It took me a while to understand the root cause of the error but now it works just fine. This is the same patch I [apply](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/rust/cargo-cross/default.nix#L21-L26) in the official Nix package.

**Comment by reitermarkus** [comment]
> It explains how the Nix store works and more.

Okay, I understand now what the Nix store does.

> it cannot find the binaries it runs inside the container

I'm still not sure what specifically the problem is though. Let me know if the following assumption is correct.

Let's say we are talking about the `cargo` binary:

- We mount the `rustup` toolchain into the container.
- The toolchain's `./bin/cargo` is not a binary but a symlink into the Nix store. 
- Calling `cargo` fails since the Nix store is not mounted.

**Comment by otavio** [comment]
Exactly, your understanding is correct. Doing the mount inside the container allows it to run successfully.

**Comment by reitermarkus** [comment]
Just one more question. Does Nix use some kind of customized version of `rustup` or how does symlinking the toolchain bineries into Nix store happen? I'd assume `rustup` just installs a complete pre-built toolchain from a tarball. Or is this a custom toolchain installed by Nix and not `rustup`?

**Comment by otavio** [comment]
Yes, it does. See [rustup](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/rust/rustup/default.nix).

**Review by reitermarkus — APPROVED** [review]

**Comment by otavio** [comment]
Should I do anything on my side on this one?

**Comment by Emilgardis** [comment]
fix the fmt error and it should be good to go :)

https://github.com/cross-rs/cross/runs/5578287402?check_suite_focus=true#step:4:10

bors d+

**Comment by Emilgardis** [comment]
yeah, thought so. Should maybe fix that in upstream bors

**Review by Emilgardis — APPROVED** [review]
bors r+

**Pull request merged**
