### PR TITLE
fix wrong usage of bool_from_envvar

### LINKED ISSUE #996: Unable to build with flag `--quiet`.
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

When adding the flag `--quiet` or  `-q` an error appear.

### What target(s) are you cross-compiling for?

x86_64-unknown-linux-musl

### Which operating system is the host (e.g computer cross is on) running?

- [X] macOS
- [ ] Windows
- [ ] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.4 (347730d 2022-08-12)

### Example

```
$ cross build -q                                      
[cross] error: cannot set both --verbose and --quiet
```

```
$ cross build --quiet
[cross] error: cannot set both --verbose and --quiet
```

### Additional information / notes

_No response_

### PR DESCRIPTION
**Pull request by Emilgardis**
fixes #996

### CODE REVIEW

**Comment by Emilgardis** [comment]
haven't tried this, but assuming it'll fix it

bors try --target dragonfly

**Comment by Emilgardis** [comment]
does the kvm inclusion need a changelog mention? I think it's fine

**Comment by Alexhuszagh** [comment]
> does the kvm inclusion need a changelog mention? I think it's fine

I don't think so, lgtm

**Review by Alexhuszagh — APPROVED** [review]

**Pull request merged**
