### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `codespell -L crate,pullrequest,ro,ot`

### CODE REVIEW

**Review by Emilgardis — APPROVED** [review]
thanks

bors r+

**Comment by Emilgardis** [comment]
need the kvm stuff done in #997

**Review by Alexhuszagh — APPROVED** [review]

**Comment by Emilgardis** [comment]
bors r=emilgardis,alexhuszagh

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
