### PR TITLE
Add `thumbv7neon-*` targets.

### LINKED ISSUE #254: Add new `thumbv7neon_linux_androideabi` and `thumbv7neon-unknown-linux-gnueabihf` targets
Originally Rust's `armv7-` targets hard-coded NEON support. However, that was changed in https://github.com/rust-lang/rust/issues/47765.

https://github.com/rust-lang/rust/issues/49897 tracks adding new `thumbv7neon-` targets that act like the old targets. See also the PR https://github.com/rust-lang/rust/pull/56947 that adds them.

These targets are very useful since a lot of the time we know that NEON is going to be available on the target. The Rust issue above notes "Firefox opts not to support ARMv7 devices that don't have it," for example. I've also had people ask for versions of my software that assume NEON is available.

### PR DESCRIPTION
**Pull request by Alexhuszagh**
Add the `thumbv7neon-linux-androideabi` and `thumbv7neon-unknown-linux-gnueabihf` targets.
    
Closes #254.

### CODE REVIEW

**Comment by Alexhuszagh** [comment]
bors try --target thumbv7neon-unknown-linux-gnueabihf

**Comment by Alexhuszagh** [comment]
OK I'm pretty certain the failing runner is due to the older Qemu version: we need Cortex-A12 or higher to support these thumbv7neon features I believe, and Qemu 5.10 only supports up to Cortex-A9. See the features of [ARM processors](https://en.wikipedia.org/wiki/List_of_ARM_processors). I might be able to get this to work by updating the Qemu version.

**Comment by Alexhuszagh** [comment]
bors try --target thumbv7neon-linux-androideabi --target thumbv7neon-unknown-linux-gnueabihf --target thumbv7neon-unknown-linux-musleabihf

**Comment by Alexhuszagh** [comment]
bors cancel
bors try --target thumbv7neon-linux-androideabi --target thumbv7neon-unknown-linux-gnueabihf

**Comment by Alexhuszagh** [comment]
Update: Forgot that `thumbv7neon-unknown-linux-musleabihf` is tier 3, and therefore doesn't have a standard library.

**Comment by Alexhuszagh** [comment]
bors try --target thumbv7neon-linux-androideabi --target thumbv7neon-unknown-linux-gnueabihf

**Comment by otavio** [comment]
Anything still pending for this?

**Comment by Alexhuszagh** [comment]
@otavio Don't believe so, if the changes look good we should be able to merge. I've checked the readelf architecture output and it looks good.

**Review by otavio — APPROVED** [review]

**Comment by Alexhuszagh** [comment]
bors r-

This is going to conflict with #746, going to have to rebase it slightly. I'll merge this with `bors r=Otavio` when the other is merged and this is rebased.

**Comment by Alexhuszagh** [comment]
EDIT: I may be wrong. My mistake, I think I undid those issues. I guess the seccomp isn't going to conflict.

bors r=Otavio

**Pull request merged**
