### PR TITLE
feat: add loongarch64-unknown-linux-musl image

### LINKED ISSUE #1556: loongarch64-linux-musl support
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar request
- [ ] This feature could be solved with a [custom image](https://github.com/cross-rs/cross/blob/main/docs/custom_images.md#custom-images) (optional)

### Describe your request

Since 1.81.0, Rust has added `loongarch64-unknown-linux-musl` as a tier 2 level target.

https://doc.rust-lang.org/nightly/releases.html#version-1810-2024-09-05

Publish a cross image for generating `loongarch64-unknown-linux-musl` application binaries.

### Describe why this would be a good inclusion for `cross`

Complete the span of available Rust targets more fully, so that Rust application developers can more easily support diverse platforms.

### PR DESCRIPTION
**Pull request by heiher**
Close #1556

### CODE REVIEW

**Comment by heiher** [comment]
@Emilgardis gentle ping.

**Comment by Emilgardis** [comment]
Thank you for the ping! I didn't see this in my inbox!

**Review by Emilgardis — APPROVED** [review]
great! lgtm!

**Comment by heiher** [comment]
CI issue: https://github.com/cross-rs/rust-cmake-hello-world/pull/1

**Pull request merged**
