### PR TITLE
Upgrade qemu to 5.1

### PR DESCRIPTION
**Pull request by malbarbo**

### CODE REVIEW

**Comment by brainstorm** [comment]
Fixes #428

**Review by reitermarkus — DISMISSED** [review]

**Comment by reitermarkus** [comment]
Can you rebase this?

**Comment by malbarbo** [comment]
Rebased. I expect some errors on centos. Let's see.

**Comment by Alexhuszagh** [comment]
We've updated the Qemu versions as these [changes](https://github.com/cross-rs/cross/pull/609/files#diff-641d3dbb849b89983593fe87f175633e9ea20625d1ccda8c8dad12a2eeefeeb4) were merged as part of #609.

**Pull request closed without merging**
