### PR TITLE
Add mirrors for file downloads.

### PR DESCRIPTION
**Pull request by Alexhuszagh**

### CODE REVIEW

**Comment by Alexhuszagh** [comment]
bors try --target x86_64-unknown-netbsd

**Comment by Alexhuszagh** [comment]
This should fix the current issues with dropbear and provide some resiliency with official mirrors only. If the release is hosted on Github or is an official Rust mirror, we don't provide another mirror.

**Comment by Alexhuszagh** [comment]
bors try --target x86_64-unknown-netbsd

**Review by Emilgardis — APPROVED** [review]
bors r+

**Pull request merged**
