### PR TITLE
use new color-eyre function to optionally display location section

### PR DESCRIPTION
**Pull request by Emilgardis**

### CODE REVIEW

**Comment by Emilgardis** [comment]
why is changelog check not working?

**Comment by Alexhuszagh** [comment]
> why is changelog check not working? @Alexhuszagh

This is definitely a bug, let me check.

**Comment by Alexhuszagh** [comment]
Seems like the `readarray` steps are failing and reading 1 array element when are none are present, so it never notices missing changes. It seems like `jq` always has an input item, which seems like an issue.

```bash
# no single quotes
$ readarray -t removed <<<"$(jq -r '.[]' <<< [])"
$ removed_count=${#removed[@]}
$ echo $removed_count
1

# with single quotes
$ readarray -t removed <<<"$(jq -r '.[]' <<< '[]')"
$ removed_count=${#removed[@]}
$ echo $removed_count
1
```

**Review by Alexhuszagh — APPROVED** [review]

**Pull request merged**
