### PR TITLE
Add experimental Xtensa targets.

### PR DESCRIPTION
**Pull request by reitermarkus**
Sources:

https://github.com/MabezDev/rust-xtensa
https://github.com/ctron/rust-esp-container

### CODE REVIEW

**Comment by reitermarkus** [comment]
bors try

**Comment by marcelbuesing** [comment]
Is there some way to use this already while the PR has not been merged yet, e.g. using the custom Docker Image?

**Comment by reitermarkus** [comment]
bors try

**Comment by reitermarkus** [comment]
bors try

**Comment by svenstaro** [comment]
@reitermarkus can you rebase this?

**Comment by Alexhuszagh** [comment]
Looks great as long as the code is rebased, this would be an excellent addition.

**Comment by Alexhuszagh** [comment]
I think this might actually be perfect for https://github.com/cross-rs/cross-toolchains (currently private), since these don't have any formal support, and therefore builds might be quite slow and/or slow down or CI. It is perfect though to have recipes that are pre-defined that are **likely** to work, which these targets fall into.

**Comment by Alexhuszagh** [comment]
I'm closing this since it should be implemented in [cross-toolchains](https://github.com/cross-rs/cross-toolchains), since these are not supported targets, not even tier 3. However, an implementation of these for custom builds would be greatly appreciated.

**Pull request closed without merging**
