### PR TITLE
Do not keep stdin open when running containers.

### PR DESCRIPTION
**Pull request by Alexhuszagh**

### CODE REVIEW

**Comment by Alexhuszagh** [comment]
This isn't expected, and can cause issues when running in parallel situations where the script assumes that it's running where the parent has stdin attached. This isn't needed, since we never request input from stdin.

**Comment by Alexhuszagh** [comment]
bors r=Emilgardis

**Comment by Alexhuszagh** [comment]
bors try --target armv5te-unknown-linux-gnueabi

**Comment by Alexhuszagh** [comment]
Looks like it was just a temporary network issue.
bors r=Emilgardis

**Comment by Emilgardis** [comment]
bors retry

**Comment by Alexhuszagh** [comment]
bors retry

**Comment by Emilgardis** [comment]
bors retry

what's wrong with ci???

**Comment by Emilgardis** [comment]
The error we're getting is

```
error: failed to solve: failed to copy: local error: tls: bad record MAC
```

**Pull request merged**
