### PR TITLE
use signal-hook instead of ctrlc

### LINKED ISSUE #1264: Suddenly unusable on CircleCI "machine" VMs
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

I use CircleCI to run cross-compile jobs using `cross` for [Geph](https://github.com/geph-official/geph4-client). To avoid the complications of docker-in-docker, I've always used the "machine" class, which spins up a full virtual machine.

Recently, my build scripts have suddenly started failing with this error:

```
#!/bin/bash -eo pipefail
cross build --release --locked  --target armv7-unknown-linux-musleabihf
Error: 
   0: Ctrl-C error: Ctrl-C signal handler already registered

Exited with code exit status 1
CircleCI received exit code 1
```

This happened even though the `cross` utility did not change versions, and my build script did not change. I suspect it's some issue with the docker container itself; it looks like some conflict with whatever code handles "ctrl+c" gracefully shutting down the docker container, conflicting with a signal handler that circleci attaches, possibly to handle the "stop compile" button.

### What target(s) are you cross-compiling for?

_No response_

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.5

### Example

_No response_

### Additional information / notes

_No response_

### PR DESCRIPTION
**Pull request by Emilgardis**
Fixes #1264

### CODE REVIEW

**Comment by Detegr** [comment]
This change is not functionally equivalent to using Ctrlc with `termination` feature. You're now handling `SIGINT` only, where previously you were handling `SIGTERM` and `SIGHUP` also.

**Comment by Emilgardis** [comment]
@Detegr noted, I wonder if that would be an issue.

**Comment by Detegr** [comment]
It depends whether you want to have for example `kill cross` run the handler or not. I'm not sure if `cross` can be used on Windows, but on Windows killing a process from a task manager or closing the command line window will trigger `CTRL_CLOSE_EVENT` and that won't be handled either.

For just exiting the process with Ctrl-C will work with this solution in unixes and Windows.

**Comment by Emilgardis** [comment]
@Detegr I see that you've reverted the behaviour in ctrlc to how it used to be and introduced try_set_handler instead. Does that mean this pr could be reverted with that update?

**Comment by Detegr** [comment]
Yes, I brought the previous overwriting behavior back as it broke more things than I anticipated (should've been a major number change, I guess).

**Pull request merged**
