### PR TITLE
release version 0.2.3

### PR DESCRIPTION
**Pull request by Emilgardis**

### CODE REVIEW

**Review by Dylan-DPC — APPROVED** [review]

**Comment by Emilgardis** [comment]
bors cancel

cross image is failing due to not finding `cross:0.2.3`

**Review by Alexhuszagh — APPROVED** [review]

**Comment by Emilgardis** [comment]
bors r=Alexhuszagh,Dylan-DPC

**Comment by Emilgardis** [comment]
bors cancel

same issue, but in dind test

**Comment by Emilgardis** [comment]
bors r=Alexhuszagh,Dylan-DPC

**Comment by Alexhuszagh** [comment]
Docker-in-Docker is still using the wrong [image](https://github.com/cross-rs/cross/runs/7257201217?check_suite_focus=true#step:5:466).

**Review by Alexhuszagh — APPROVED** [review]

**Review by Alexhuszagh — CHANGES_REQUESTED** [review]
Should be fixed by another PR.

**Review by Alexhuszagh — APPROVED** [review]

**Comment by Emilgardis** [comment]
bors r=Alexhuszagh,Dylan-DPC

**Pull request merged**
